export type ZamolxisErrorCode =
  | "NOT_FOUND"
  | "FORBIDDEN"
  | "INVALID_STATE"
  | "WORKSPACE_BUSY"
  | "WORKSPACE_MISMATCH"
  | "WORKSTATION_OFFLINE"
  | "RUNTIME_UNAVAILABLE"
  | "COMMAND_CONFLICT"
  | "DEPENDENCY_CYCLE"
  | "APPROVAL_REQUIRED"
  | "RECONCILIATION_REQUIRED";
